// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI-gPNu7msk5WB2MdtcTb8mypN3LoNzoU',
    appId: '1:523990087851:web:e74835d098c2d43e9edfee',
    messagingSenderId: '523990087851',
    projectId: 'qbite-594eb',
    authDomain: 'qbite-594eb.firebaseapp.com',
    storageBucket: 'qbite-594eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb8X7Y6T7kvxbhIeH8jVRmgCrWTUHeuQc',
    appId: '1:523990087851:android:f672c413c3bf927b9edfee',
    messagingSenderId: '523990087851',
    projectId: 'qbite-594eb',
    storageBucket: 'qbite-594eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuigFmyAza2J2mq-sBx-gKksX37eIurAo',
    appId: '1:523990087851:ios:7507793ae546f5369edfee',
    messagingSenderId: '523990087851',
    projectId: 'qbite-594eb',
    storageBucket: 'qbite-594eb.firebasestorage.app',
    iosBundleId: 'com.example.qbite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuigFmyAza2J2mq-sBx-gKksX37eIurAo',
    appId: '1:523990087851:ios:7507793ae546f5369edfee',
    messagingSenderId: '523990087851',
    projectId: 'qbite-594eb',
    storageBucket: 'qbite-594eb.firebasestorage.app',
    iosBundleId: 'com.example.qbite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI-gPNu7msk5WB2MdtcTb8mypN3LoNzoU',
    appId: '1:523990087851:web:63220fa1a8b6daa89edfee',
    messagingSenderId: '523990087851',
    projectId: 'qbite-594eb',
    authDomain: 'qbite-594eb.firebaseapp.com',
    storageBucket: 'qbite-594eb.firebasestorage.app',
  );
}
